// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9pQIleMXi6SJUmw0ZdF4F71FkxCS6VYs',
    appId: '1:880088681955:web:4fb11efd9050b59eda64d6',
    messagingSenderId: '880088681955',
    projectId: 'akhisapp-3aa36',
    authDomain: 'akhisapp-3aa36.firebaseapp.com',
    storageBucket: 'akhisapp-3aa36.firebasestorage.app',
    measurementId: 'G-0NWM32J73G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSjT2XV7MMxmX343BNvlyr9dEtF4s1kLU',
    appId: '1:880088681955:android:76a101b63679a1a9da64d6',
    messagingSenderId: '880088681955',
    projectId: 'akhisapp-3aa36',
    storageBucket: 'akhisapp-3aa36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0kuOPqjx2J8t4FGLg1evITBJX3__q0og',
    appId: '1:880088681955:ios:3c29396dbafa32fdda64d6',
    messagingSenderId: '880088681955',
    projectId: 'akhisapp-3aa36',
    storageBucket: 'akhisapp-3aa36.firebasestorage.app',
    iosBundleId: 'com.example.akhisarapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0kuOPqjx2J8t4FGLg1evITBJX3__q0og',
    appId: '1:880088681955:ios:3c29396dbafa32fdda64d6',
    messagingSenderId: '880088681955',
    projectId: 'akhisapp-3aa36',
    storageBucket: 'akhisapp-3aa36.firebasestorage.app',
    iosBundleId: 'com.example.akhisarapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9pQIleMXi6SJUmw0ZdF4F71FkxCS6VYs',
    appId: '1:880088681955:web:864bb4288a558840da64d6',
    messagingSenderId: '880088681955',
    projectId: 'akhisapp-3aa36',
    authDomain: 'akhisapp-3aa36.firebaseapp.com',
    storageBucket: 'akhisapp-3aa36.firebasestorage.app',
    measurementId: 'G-GX1KMEQ8KH',
  );
}
